name: Package Application with Pyinstaller

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v2

    - name: NPM install & Gulp
      run: npm install

    - name: Build assets
      run: gulp


    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.x

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
      working-directory: ./


    - name: Build executable
      run: |
        pyinstaller --clean --onefile --windowed --noconfirm --add-data "./assets" --icon "./icon.ico" --name "ctjsWebInstaller" start.py
      working-directory: ./

    - name: Create Artifact (Windows)
      uses: actions/upload-artifact@v3
      with:
        name: windows-executables
        path: /dist/*.exe

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUBTOKEN }}

    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUBTOKEN }}"
        automatic_release_tag: ${{ steps.tag_version.outputs.new_tag }}
        prerelease: false
        files: |
          ./dist/*.exe
